/**
 * AUTO-GENERATED from index.md — DO NOT EDIT MANUALLY
 *
 * ⚠️  IMPORTANT: This file is automatically generated!
 * To update navigation structure, edit: /content/6_1/index.md
 * Then run: npm run sync-toc
 *
 * SINGLE SOURCE OF TRUTH: /content/<version>/index.md files
 *
 * Generated: 2026-04-20T07:43:22.960Z
 * Source: /content/6_1/index.md
 */

// Module definitions
export const modules = [
  { id: "my-dashboard", label: "My Dashboard" },
  { id: "cmdb", label: "CMDB" },
  { id: "discovery-scan", label: "Discovery Scan" },
  { id: "itsm", label: "ITSM" },
  { id: "vulnerability-management", label: "Vulnerability Management" },
  { id: "itam", label: "ITAM" },
  { id: "programproject-management", label: "Program/Project Management" },
  { id: "self-service", label: "Self-Service" },
  { id: "risk-register", label: "Risk Register" },
  { id: "reports", label: "Reports" },
  { id: "admin", label: "Admin" },
  { id: "release-notes", label: "Release Notes" },
  { id: "support", label: "Support" },
];

// Version definitions — only 6.1 is active; other versions reserved for future use
export const versions = ["6.1"];

// My Dashboard sections
export const myDashboardSections = [
  {
    id: "getting-started",
    title: "Getting Started",
    label: "Getting Started",
    pages: [
      {
        id: "authentication",
        label: "Authentication",
        path: "`/content/6_1/getting_started_6_1/authentication_6_1.md`"
      },
      {
        id: "organisation-details",
        label: "Organisation Details",
        path: "`/content/6_1/getting_started_6_1/organization_details_6_1.md`"
      },
      {
        id: "sso-and-authentication",
        label: "SSO and Authentication",
        path: "`/content/6_1/getting_started_6_1/sso_authentication_6_1.md`"
      },
      {
        id: "user-management",
        label: "User Management",
        path: "`/content/6_1/getting_started_6_1/user_management_6_1.md`"
      },
      {
        id: "branding",
        label: "Branding",
        path: "`/content/6_1/getting_started_6_1/branding_6_1.md`"
      },
      {
        id: "user-settings",
        label: "User Settings",
        path: "`/content/6_1/getting_started_6_1/organization_details_6_1.md`"
      }
    ]
  },
  {
    id: "application-overview",
    title: "Application Overview",
    label: "Application Overview",
    pages: [
      {
        id: "application-overview",
        label: "Application Overview",
        path: "`/content/6_1/application_overview_6_1/all_about_virima_6_1.md`"
      },
      {
        id: "system-icons",
        label: "System Icons",
        path: "`/content/6_1/application_overview_6_1/icons_6_1.md`"
      },
      {
        id: "user-specific-functions",
        label: "User Specific Functions",
        path: "`/content/6_1/application_overview_6_1/user_specific_functions_6_1.md`",
        subPages: [
          {
            id: "advanced-search",
            label: "Advanced Search",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/advanced_search_6_1.md`"
          },
          {
            id: "attachments",
            label: "Attachments",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/attachments_6_1.md`"
          },
          {
            id: "auto-refresh",
            label: "Auto Refresh",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/auto_refresh_6_1.md`"
          },
          {
            id: "collapsemaximize",
            label: "Collapse/Maximize",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/collapse_maximize_6_1.md`"
          },
          {
            id: "comments",
            label: "Comments",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/comments_6_1.md`"
          },
          {
            id: "deleteremove",
            label: "Delete/Remove",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/delete_remove_6_1.md`"
          },
          {
            id: "email-preferences",
            label: "Email Preferences",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/email_prefs_6_1.md`"
          },
          {
            id: "enabledisable-editing",
            label: "Enable/Disable Editing",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/enable_disable_editing_6_1.md`"
          },
          {
            id: "export",
            label: "Export",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/export_6_1.md`"
          },
          {
            id: "filter-by",
            label: "Filter By",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/filter_by_6_1.md`"
          },
          {
            id: "history",
            label: "History",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/history_6_1.md`"
          },
          {
            id: "import",
            label: "Import",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/import_6_1.md`"
          },
          {
            id: "items-per-page",
            label: "Items per Page",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/items_per_page_6_1.md`"
          },
          {
            id: "mark-as-knowledge",
            label: "Mark as Knowledge",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/mark_as_knowledge_6_1.md`"
          },
          {
            id: "other-asset-info",
            label: "Other Asset Info",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/other_asset_info_6_1.md`"
          },
          {
            id: "outage-calendar",
            label: "Outage Calendar",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/outage_calendar_6_1.md`"
          },
          {
            id: "personalize-columns",
            label: "Personalize Columns",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/personalize_columns_6_1.md`"
          },
          {
            id: "print",
            label: "Print",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/print_6_1.md`"
          },
          {
            id: "records-per-page",
            label: "Records per Page",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/records_per_page_6_1.md`"
          },
          {
            id: "reload-default-mapping",
            label: "Reload Default Mapping",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/reload_default_mapping_6_1.md`"
          },
          {
            id: "re-scan",
            label: "Re-scan",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/re_scan_6_1.md`"
          },
          {
            id: "re-sync-data",
            label: "Re-Sync Data",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/re_sync_data_6_1.md`"
          },
          {
            id: "save",
            label: "Save",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/save_6_1.md`"
          },
          {
            id: "saved-filters",
            label: "Saved Filters",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/saved_filters_6_1.md`"
          },
          {
            id: "searching",
            label: "Searching",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/searching_6_1.md`"
          },
          {
            id: "show-mainall-properties",
            label: "Show Main/All Properties",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/show_main_all_properties_6_1.md`"
          },
          {
            id: "tasks",
            label: "Tasks",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/tasks_6_1.md`"
          },
          {
            id: "updates",
            label: "Updates",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/updates_6_1.md`"
          },
          {
            id: "version-control",
            label: "Version Control",
            path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/version_control_6_1.md`"
          }
        ]
      },
      {
        id: "online-help",
        label: "Online Help",
        path: "`/content/6_1/application_overview_6_1/online_help_6_1.md`"
      }
    ]
  },
  {
    id: "dashboards",
    title: "Dashboards",
    label: "Dashboards",
    pages: [
      {
        id: "contents",
        label: "Contents",
        path: "`/content/6_1/dashboard_6_1/dashboard_add_contents_new_6_1.md`"
      },
      {
        id: "customization",
        label: "Customization",
        path: "`/content/6_1/dashboard_6_1/dashboard_customization_6_1.md`",
        subPages: [
          {
            id: "overview",
            label: "Overview",
            path: "`/content/6_1/dashboard_6_1/my_dashboard_new_6_1.md`"
          },
          {
            id: "contents",
            label: "Contents",
            path: "`/content/6_1/dashboard_6_1/dashboard_add_contents_new_6_1.md`"
          },
          {
            id: "report-actions",
            label: "Report Actions",
            path: "`/content/6_1/dashboard_6_1/dashboard_reports_actions_6_1.md`"
          }
        ]
      }
    ]
  }
];

// CMDB sections
export const cmdbSections = [
  {
    id: "getting-started",
    title: "Getting Started",
    label: "Getting Started",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/cmdb_6_1/cmdb_overview_6_1.md`"
      },
      {
        id: "access-cmdb",
        label: "Access CMDB",
        path: "`/content/6_1/cmdb_6_1/access_cmdb_6_1.md`"
      }
    ]
  },
  {
    id: "manage-cmdb",
    title: "Manage CMDB",
    label: "Manage CMDB",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/cmdb_6_1/manage_cmdb_6_1.md`"
      },
      {
        id: "audits",
        label: "Audits",
        path: "`/content/6_1/cmdb_6_1/audits_6_1.md`",
        subPages: [
          {
            id: "change-attributes",
            label: "Change Attributes",
            path: "`/content/6_1/cmdb_6_1/change_attributes_6_1.md`"
          },
          {
            id: "delete",
            label: "Delete",
            path: "`/content/6_1/cmdb_6_1/delete_6_1.md`"
          },
          {
            id: "export",
            label: "Export",
            path: "`/content/6_1/cmdb_6_1/export_6_1.md`"
          },
          {
            id: "new",
            label: "New",
            path: "`/content/6_1/cmdb_6_1/new_6_1.md`"
          },
          {
            id: "copy-to-ivanti",
            label: "Copy to Ivanti",
            path: "`/content/6_1/cmdb_6_1/copy_to_ivanti_6_1.md`"
          },
          {
            id: "copy-to-jira",
            label: "Copy to Jira",
            path: "`/content/6_1/cmdb_6_1/copy_to_jira_6_1.md`"
          },
          {
            id: "copy-to-servicenow",
            label: "Copy to ServiceNow",
            path: "`/content/6_1/cmdb_6_1/copy_to_servicenow_6_1.md`"
          },
          {
            id: "generate-installed-software-report",
            label: "Generate Installed Software Report",
            path: "`/content/6_1/cmdb_6_1/generate_installed_software_report_6_1.md`"
          },
          {
            id: "process-adm",
            label: "Process ADM",
            path: "`/content/6_1/cmdb_6_1/process_adm_6_1.md`"
          },
          {
            id: "process-available-patch-report",
            label: "Process Available Patch Report",
            path: "`/content/6_1/cmdb_6_1/process_available_patch_report_6_1.md`"
          },
          {
            id: "process-cloud-hierarchy",
            label: "Process Cloud Hierarchy",
            path: "`/content/6_1/cmdb_6_1/process_cloud_hierarchy_6_1.md`"
          },
          {
            id: "process-devops",
            label: "Process DevOps",
            path: "`/content/6_1/cmdb_6_1/process_devops_6_1.md`"
          },
          {
            id: "process-missing-components",
            label: "Process Missing Components",
            path: "`/content/6_1/cmdb_6_1/process_missing_components_6_1.md`"
          },
          {
            id: "process-network-connection",
            label: "Process Network Connection",
            path: "`/content/6_1/cmdb_6_1/process_network_connection_6_1.md`"
          },
          {
            id: "process-software-installation",
            label: "Process Software Installation",
            path: "`/content/6_1/cmdb_6_1/process_software_installation_6_1.md`"
          },
          {
            id: "process-network-virtualization-hierarchy",
            label: "Process Network Virtualization Hierarchy",
            path: "`/content/6_1/cmdb_6_1/proces_network_virtualization_hierarchy_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "view-and-edit-a-ci",
    title: "View and Edit a CI",
    label: "View and Edit a CI",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/cmdb_6_1/view_and_edit_a_ci_6_1.md`",
        subPages: [
          {
            id: "ci-left-panel",
            label: "CI Left Panel",
            path: "`/content/6_1/cmdb_6_1/ci_left_panel_6_1.md`"
          },
          {
            id: "contacts-on-a-ci",
            label: "Contacts on a CI",
            path: "`/content/6_1/cmdb_6_1/contacts_on_a_ci_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "ci-details-and-tabs",
    title: "CI Details and Tabs",
    label: "CI Details and Tabs",
    pages: [
      {
        id: "ci-details-and-tabs",
        label: "CI Details and Tabs",
        path: "`/content/6_1/cmdb_6_1/ci_details_and_tabs_6_1.md`",
        subPages: [
          {
            id: "details",
            label: "Details",
            path: "`/content/6_1/cmdb_6_1/details_6_1.md`",
            subPages: [
              {
                id: "manage-ci",
                label: "Manage CI",
                path: "`/content/6_1/cmdb_6_1/manage_ci_6_1.md`"
              },
              {
                id: "business-service-map",
                label: "Business Service Map",
                path: "`/content/6_1/cmdb_6_1/business_service_map_6_1.md`"
              }
            ]
          },
          {
            id: "components",
            label: "Components",
            path: "`/content/6_1/cmdb_6_1/components_6_1.md`"
          },
          {
            id: "logon-events",
            label: "Logon Events",
            path: "`/content/6_1/cmdb_6_1/logon_events_6_1.md`"
          },
          {
            id: "itsm",
            label: "ITSM",
            path: "`/content/6_1/cmdb_6_1/itsm_6_1.md`"
          },
          {
            id: "relationships",
            label: "Relationships",
            path: "`/content/6_1/cmdb_6_1/relationships_6_1.md`"
          },
          {
            id: "audits",
            label: "Audits",
            path: "`/content/6_1/cmdb_6_1/audits_tab_6_1.md`"
          },
          {
            id: "sla",
            label: "SLA",
            path: "`/content/6_1/cmdb_6_1/sla_6_1.md`"
          },
          {
            id: "maintenance",
            label: "Maintenance",
            path: "`/content/6_1/cmdb_6_1/maintenance_6_1.md`"
          },
          {
            id: "vulnerability",
            label: "Vulnerability",
            path: "`/content/6_1/cmdb_6_1/vulnerability_6_1.md`"
          },
          {
            id: "private-properties",
            label: "Private Properties",
            path: "`/content/6_1/cmdb_6_1/private_properties_6_1.md`"
          },
          {
            id: "tasks",
            label: "Tasks",
            path: "`/content/6_1/cmdb_6_1/tasks_6_1.md`"
          },
          {
            id: "history",
            label: "History",
            path: "`/content/6_1/cmdb_6_1/history_6_1.md`"
          },
          {
            id: "attachments",
            label: "Attachments",
            path: "`/content/6_1/cmdb_6_1/attachments_6_1.md`"
          },
          {
            id: "comments",
            label: "Comments",
            path: "`/content/6_1/cmdb_6_1/comments_6_1.md`"
          }
        ]
      },
      {
        id: "other-functions-and-page-elements",
        label: "Other Functions and Page Elements",
        path: "`/content/6_1/cmdb_6_1/other_functions_and_page_elements_6_1.md`"
      }
    ]
  }
];

// Discovery Scan sections
export const discoveryScanSections = [
  {
    id: "dashboard",
    title: "Dashboard",
    label: "Dashboard",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/dashboard/dashboard_discovery_scan_new_6_1.md`"
      },
      {
        id: "access-dashboard",
        label: "Access Dashboard",
        path: "`/content/6_1/discovery_6_1/dashboard/access_dashboard_6_1.md`",
        subPages: [
          {
            id: "dashboard-features",
            label: "Dashboard Features",
            path: "`/content/6_1/discovery_6_1/dashboard/dashboard_features_6_1.md`"
          },
          {
            id: "add-contents",
            label: "Add Contents",
            path: "`/content/6_1/discovery_6_1/dashboard/add_contents_6_1.md`"
          },
          {
            id: "dashboard-customization",
            label: "Dashboard Customization",
            path: "`/content/6_1/discovery_6_1/dashboard/dashboard_customization_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "run-a-scan",
    title: "Run a Scan",
    label: "Run a Scan",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/run_a_scan/run_a_scan_6_1.md`"
      },
      {
        id: "pre-requisites-for-scan",
        label: "Pre-requisites for Scan",
        path: "`/content/6_1/discovery_6_1/run_a_scan/scans_pre_reqs_6_1.md`"
      }
    ]
  },
  {
    id: "recent-scans",
    title: "Recent Scans",
    label: "Recent Scans",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/recent_scans/scans_recent_6_1.md`"
      },
      {
        id: "access-recent-scan",
        label: "Access Recent Scan",
        path: "`/content/6_1/discovery_6_1/recent_scans/access_recent_scan_6_1.md`",
        subPages: [
          {
            id: "view-recent-scan",
            label: "View Recent Scan",
            path: "`/content/6_1/discovery_6_1/recent_scans/view_recent_scan_6_1.md`",
            subPages: [
              {
                id: "details",
                label: "Details",
                path: "`/content/6_1/discovery_6_1/recent_scans/details_recentscans_6_1.md`",
                subPages: [
                  {
                    id: "export-scan-report",
                    label: "Export Scan Report",
                    path: "`/content/6_1/discovery_6_1/recent_scans/export_scan_report_6_1.md`"
                  },
                  {
                    id: "refresh",
                    label: "Refresh",
                    path: "`/content/6_1/discovery_6_1/recent_scans/refresh_recentscans_6_1.md`"
                  }
                ]
              },
              {
                id: "logs",
                label: "Logs",
                path: "`/content/6_1/discovery_6_1/recent_scans/logs_recentscans_6_1.md`"
              },
              {
                id: "tasks",
                label: "Tasks",
                path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/tasks_6_1.md`"
              },
              {
                id: "comments",
                label: "Comments",
                path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/comments_6_1.md`"
              },
              {
                id: "attachments",
                label: "Attachments",
                path: "`/content/6_1/application_overview_6_1/shared_fucntions_6_1/attachments_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "scheduled-scans-and-imports",
    title: "Scheduled Scans and Imports",
    label: "Scheduled Scans and Imports",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/schedule_scans_import_6_1.md`"
      },
      {
        id: "pre-requisites",
        label: "Pre-requisites",
        path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/prerequisites_scheduledscanimports_6_1.md`",
        subPages: [
          {
            id: "accessing-scheduled-scan-and-imports",
            label: "Accessing Scheduled Scan and Imports",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/accessing_scheduled_scan_imports_6_1.md`"
          },
          {
            id: "key-features-and-options-on-the-landing-page",
            label: "Key Features and Options on the Landing Page",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/key_features_options_landing_page_6_1.md`"
          },
          {
            id: "scans-and-import-options",
            label: "Scans and Import Options",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/scans_import_options_6_1.md`",
            subPages: [
              {
                id: "scan-and-import-schedule-list",
                label: "Scan and Import Schedule List",
                path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/scan_import_schedule_list_6_1.md`"
              }
            ]
          },
          {
            id: "schedule-a-network-scan",
            label: "Schedule a Network Scan",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/schedule_network_scan_6_1.md`"
          },
          {
            id: "editing-a-scheduled-scan",
            label: "Editing a Scheduled Scan",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/editing_scheduled_scan_6_1.md`"
          },
          {
            id: "history-of-scheduled-scan-execution",
            label: "History of Scheduled Scan Execution",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/history_scheduled_scan_execution_6_1.md`"
          },
          {
            id: "bulk-update-scan",
            label: "Bulk Update Scan",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/bulk_update_scan_6_1.md`"
          },
          {
            id: "exporting-a-scan",
            label: "Exporting a Scan",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/exporting_scan_6_1.md`"
          },
          {
            id: "importing-scan-schedules",
            label: "Importing Scan Schedule(s)",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/importing_scan_schedule_6_1.md`"
          },
          {
            id: "deleting-a-scan-schedule",
            label: "Deleting a Scan Schedule",
            path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/deleting_scan_schedule_6_1.md`",
            subPages: [
              {
                id: "aws-import",
                label: "AWS Import",
                path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/aws_import_6_1.md`"
              },
              {
                id: "azure-import",
                label: "Azure Import",
                path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/azure_import_6_1.md`"
              },
              {
                id: "meraki-import",
                label: "Meraki Import",
                path: "`/content/6_1/discovery_6_1/scheduled_scans_imports/meraki_import_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "ipam-networks",
    title: "IPAM Networks",
    label: "IPAM Networks",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/ipam_networks/ipam_networks_overview_6_1.md`"
      },
      {
        id: "ipam-procedure",
        label: "IPAM Procedure",
        path: "`/content/6_1/discovery_6_1/ipam_networks/ipam_procedure_6_1.md`",
        subPages: [
          {
            id: "infoblox-configuration",
            label: "Infoblox Configuration",
            path: "`/content/6_1/discovery_6_1/ipam_networks/infoblox_configuration_6_1.md`"
          },
          {
            id: "ipam-ip-address-management",
            label: "IPAM (IP Address Management)",
            path: "`/content/6_1/discovery_6_1/ipam_networks/ipam_ip_address_management_6_1.md`"
          },
          {
            id: "ipam-functions-overview",
            label: "IPAM Functions Overview",
            path: "`/content/6_1/discovery_6_1/ipam_networks/ipam_functions_overview_6_1.md`",
            subPages: [
              {
                id: "scan-function",
                label: "Scan Function",
                path: "`/content/6_1/discovery_6_1/ipam_networks/scan_function_6_1.md`",
                subPages: [
                  {
                    id: "status-update",
                    label: "Status Update",
                    path: "`/content/6_1/discovery_6_1/ipam_networks/status_update_6_1.md`"
                  },
                  {
                    id: "regular-scan",
                    label: "Regular Scan",
                    path: "`/content/6_1/discovery_6_1/ipam_networks/regular_scan_6_1.md`"
                  }
                ]
              }
            ]
          },
          {
            id: "sync-instant-and-scheduled",
            label: "Sync (Instant and Scheduled)",
            path: "`/content/6_1/discovery_6_1/ipam_networks/sync_instant_scheduled_6_1.md`"
          },
          {
            id: "view-and-edit-a-network",
            label: "View and Edit a Network",
            path: "`/content/6_1/discovery_6_1/ipam_networks/view_edit_network_6_1.md`"
          },
          {
            id: "other-functions-and-page-elements",
            label: "Other Functions and Page Elements",
            path: "`/content/6_1/discovery_6_1/ipam_networks/other_functions_page_elements_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "discovered-items",
    title: "Discovered Items",
    label: "Discovered Items",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/discovered_items/discovered_items_6_1.md`"
      },
      {
        id: "prerequisites",
        label: "Prerequisites",
        path: "`/content/6_1/discovery_6_1/discovered_items/prerequisites_discovered_items_6_1.md`",
        subPages: [
          {
            id: "access-discovered-items",
            label: "Access Discovered Items",
            path: "`/content/6_1/discovery_6_1/discovered_items/access_discovered_items_6_1.md`"
          },
          {
            id: "manage-discovered-items",
            label: "Manage Discovered Items",
            path: "`/content/6_1/discovery_6_1/discovered_items/manage_discovered_items_6_1.md`",
            subPages: [
              {
                id: "delete",
                label: "Delete",
                path: "`/content/6_1/discovery_6_1/discovered_items/delete_6_1.md`"
              },
              {
                id: "export",
                label: "Export",
                path: "`/content/6_1/discovery_6_1/discovered_items/export_6_1.md`"
              },
              {
                id: "export-without-selecting-any-record",
                label: "Export Without Selecting Any Record",
                path: "`/content/6_1/discovery_6_1/discovered_items/export_without_selecting_any_record_6_1.md`"
              },
              {
                id: "move-to-cmdb",
                label: "Move to CMDB",
                path: "`/content/6_1/discovery_6_1/discovered_items/move_to_cmdb_6_1.md`"
              },
              {
                id: "re-scan",
                label: "Re-scan",
                path: "`/content/6_1/discovery_6_1/discovered_items/re_scan_6_1.md`"
              }
            ]
          },
          {
            id: "column-descriptions",
            label: "Column Descriptions",
            path: "`/content/6_1/discovery_6_1/discovered_items/column_descriptions_6_1.md`"
          },
          {
            id: "detailed-view-of-discovered-items",
            label: "Detailed View of Discovered Items",
            path: "`/content/6_1/discovery_6_1/discovered_items/detailed_view_discovered_items_6_1.md`",
            subPages: [
              {
                id: "primary-details-block",
                label: "Primary Details Block",
                path: "`/content/6_1/discovery_6_1/discovered_items/primary_details_block_6_1.md`"
              },
              {
                id: "owner-block",
                label: "Owner Block",
                path: "`/content/6_1/discovery_6_1/discovered_items/owner_block_6_1.md`"
              },
              {
                id: "main-information-area",
                label: "Main Information Area",
                path: "`/content/6_1/discovery_6_1/discovered_items/main_information_area_6_1.md`"
              },
              {
                id: "action-buttons",
                label: "Action Buttons",
                path: "`/content/6_1/discovery_6_1/discovered_items/action_buttons_6_1.md`"
              },
              {
                id: "navigation-tabs",
                label: "Navigation Tabs",
                path: "`/content/6_1/discovery_6_1/discovered_items/navigation_tabs_6_1.md`"
              }
            ]
          },
          {
            id: "other-functions-and-page-elements",
            label: "Other Functions and Page Elements",
            path: "`/content/6_1/discovery_6_1/discovered_items/other_functions_page_elements_6_1.md`",
            subPages: [
              {
                id: "toolbar-or-control-bar",
                label: "Toolbar or Control Bar",
                path: "`/content/6_1/discovery_6_1/discovered_items/toolbar_controlbar_6_1.md`"
              },
              {
                id: "filter-by",
                label: "Filter By",
                path: "`/content/6_1/discovery_6_1/discovered_items/filter_by_discovered_items_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "import-from-aws",
    title: "Import from AWS",
    label: "Import from AWS",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/import_aws_6_1.md`"
      },
      {
        id: "access-the-import-aws-window",
        label: "Access the Import AWS Window",
        path: "`/content/6_1/discovery_6_1/import_from_aws/access_import_aws_window_6_1.md`",
        subPages: [
          {
            id: "import-aws-record",
            label: "Import AWS Record",
            path: "`/content/6_1/discovery_6_1/import_from_aws/import_aws_record_6_1.md`"
          },
          {
            id: "view-aws-import-record",
            label: "View AWS Import Record",
            path: "`/content/6_1/discovery_6_1/import_from_aws/view_aws_import_record_6_1.md`",
            subPages: [
              {
                id: "key-columns",
                label: "Key columns",
                path: "`/content/6_1/discovery_6_1/import_from_aws/key_columns_6_1.md`"
              },
              {
                id: "move-items-to-cmdb",
                label: "Move Items to CMDB",
                path: "`/content/6_1/discovery_6_1/import_from_aws/move_items_cmdb_6_1.md`"
              },
              {
                id: "logs",
                label: "Logs",
                path: "`/content/6_1/discovery_6_1/import_from_aws/logs_6_1.md`"
              }
            ]
          },
          {
            id: "delete-aws-record",
            label: "Delete AWS Record",
            path: "`/content/6_1/discovery_6_1/import_from_aws/delete_aws_record_6_1.md`"
          },
          {
            id: "export-aws-records",
            label: "Export AWS Records",
            path: "`/content/6_1/discovery_6_1/import_from_aws/export_aws_records_6_1.md`"
          },
          {
            id: "view-a-discovered-aws-record",
            label: "View a discovered AWS record",
            path: "`/content/6_1/discovery_6_1/import_from_aws/view_discovered_aws_record_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "import-from-azure",
    title: "Import from Azure",
    label: "Import from Azure",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/import_from_azure/import_azure_overview_6_1.md`"
      },
      {
        id: "access-the-import-azure-window",
        label: "Access the Import AZURE Window",
        path: "`/content/6_1/discovery_6_1/import_from_azure/access_import_azure_window_6_1.md`",
        subPages: [
          {
            id: "import-azure-record",
            label: "Import AZURE Record",
            path: "`/content/6_1/discovery_6_1/import_from_azure/import_azure_record_6_1.md`"
          },
          {
            id: "view-azure-import-record",
            label: "View AZURE Import Record",
            path: "`/content/6_1/discovery_6_1/import_from_azure/view_azure_import_record_6_1.md`",
            subPages: [
              {
                id: "common-controls-top-right-of-the-grid",
                label: "Common controls (top-right of the grid)",
                path: "`/content/6_1/discovery_6_1/import_from_azure/common_controls_6_1.md`"
              },
              {
                id: "key-columns",
                label: "Key columns",
                path: "`/content/6_1/discovery_6_1/import_from_azure/key_columns_6_1.md`"
              },
              {
                id: "move-items-to-the-cmdb",
                label: "Move items to the CMDB",
                path: "`/content/6_1/discovery_6_1/import_from_azure/move_items_cmdb_6_1.md`"
              }
            ]
          },
          {
            id: "delete-azure-record",
            label: "Delete AZURE Record",
            path: "`/content/6_1/discovery_6_1/import_from_azure/delete_azure_record_6_1.md`"
          },
          {
            id: "export-azure-records",
            label: "Export AZURE Records",
            path: "`/content/6_1/discovery_6_1/import_from_azure/export_azure_record_6_1.md`"
          },
          {
            id: "view-a-discovered-azure-record",
            label: "View a discovered AZURE record",
            path: "`/content/6_1/discovery_6_1/import_from_azure/view_discovered_azure_record_6_1.md`",
            subPages: [
              {
                id: "discovered-item-view-overview",
                label: "Discovered item view overview",
                path: "`/content/6_1/discovery_6_1/import_from_azure/discovered_item_view_overview_6_1.md`"
              },
              {
                id: "top-right-actions",
                label: "Top-right actions",
                path: "`/content/6_1/discovery_6_1/import_from_azure/top_right_actions_6_1.md`"
              },
              {
                id: "tabs-main-panel",
                label: "Tabs (main panel)",
                path: "`/content/6_1/discovery_6_1/import_from_azure/tabs_main_panel_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "import-from-meraki",
    title: "Import from Meraki",
    label: "Import from Meraki",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/import_from_meraki/import_meraki_overview_6_1.md`"
      },
      {
        id: "prerequisites",
        label: "Prerequisites",
        path: "`/content/6_1/discovery_6_1/import_from_meraki/prerequisites_meraki_6_1.md`",
        subPages: [
          {
            id: "assess-import-meraki-window",
            label: "Assess Import Meraki Window",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/assess_import_meraki_window_6_1.md`"
          },
          {
            id: "import-meraki-record",
            label: "Import Meraki Record",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/import_meraki_record_6_1.md`"
          },
          {
            id: "view-meraki-import-record",
            label: "View Meraki Import Record",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/view_meraki_import_record_6_1.md`",
            subPages: [
              {
                id: "common-controls",
                label: "Common controls",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/common_controls_6_1.md`"
              },
              {
                id: "key-columns",
                label: "Key columns",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/key_columns_6_1.md`"
              },
              {
                id: "move-items-to-the-cmdb",
                label: "Move items to the CMDB",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/move_items_cmdb_6_1.md`"
              },
              {
                id: "logs",
                label: "Logs",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/logs_6_1.md`"
              }
            ]
          },
          {
            id: "delete-meraki-record",
            label: "Delete Meraki Record",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/delete_meraki_record_6_1.md`"
          },
          {
            id: "export-meraki-records",
            label: "Export Meraki Records",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/export_meraki_records_6_1.md`"
          },
          {
            id: "view-a-discovered-meraki-record",
            label: "View a discovered Meraki record",
            path: "`/content/6_1/discovery_6_1/import_from_meraki/view_discovered_meraki_record_6_1.md`",
            subPages: [
              {
                id: "discovered-item-view-overview",
                label: "Discovered item view overview",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/discovered_item_view_overview_6_1.md`"
              },
              {
                id: "top-right-actions",
                label: "Top-right actions",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/top_right_actions_6_1.md`"
              },
              {
                id: "tabs-main-panel",
                label: "Tabs (main panel)",
                path: "`/content/6_1/discovery_6_1/import_from_meraki/tabs_main_panel_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "import-from-intune",
    title: "Import from Intune",
    label: "Import from Intune",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/import_from_intune/import_intune_overview_6_1.md`"
      },
      {
        id: "access-import-from-intune",
        label: "Access Import From Intune",
        path: "`/content/6_1/discovery_6_1/import_from_intune/access_import_intune_window_6_1.md`",
        subPages: [
          {
            id: "import-intune-record",
            label: "Import Intune Record",
            path: "`/content/6_1/discovery_6_1/import_from_intune/import_intune_record_6_1.md`"
          },
          {
            id: "view-intune-import-record",
            label: "View Intune Import Record",
            path: "`/content/6_1/discovery_6_1/import_from_intune/view_intune_import_record_6_1.md`"
          },
          {
            id: "delete-intune-record",
            label: "Delete Intune Record",
            path: "`/content/6_1/discovery_6_1/import_from_intune/delete_intune_record_6_1.md`"
          },
          {
            id: "export-intune-records",
            label: "Export Intune Records",
            path: "`/content/6_1/discovery_6_1/import_from_intune/export_intune_record_6_1.md`"
          },
          {
            id: "view-a-discovered-intune-record",
            label: "View a discovered Intune record",
            path: "`/content/6_1/discovery_6_1/import_from_intune/view_a_discovered_intune_record_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "import-data-files",
    title: "Import Data Files",
    label: "Import Data Files",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/discovery_6_1/import_data_file_6_1.md`"
      },
      {
        id: "access-the-import-data-files",
        label: "Access the Import Data Files",
        path: "`/content/6_1/discovery_6_1/import_data_files/access_the_import_data_files_6_1.md`",
        subPages: [
          {
            id: "manage-import-data-files",
            label: "Manage Import Data Files",
            path: "`/content/6_1/discovery_6_1/import_data_files/manage_import_data_files_6_1.md`",
            subPages: [
              {
                id: "import-ci",
                label: "Import CI",
                path: "`/content/6_1/discovery_6_1/import_data_files/import_ci_6_1.md`"
              },
              {
                id: "view-an-imported-data-file",
                label: "View an Imported Data File",
                path: "`/content/6_1/discovery_6_1/import_data_files/view_an_imported_data_file_6_1.md`",
                subPages: [
                  {
                    id: "all-tab",
                    label: "All Tab",
                    path: "`/content/6_1/discovery_6_1/import_data_files/all_tab_6_1.md`"
                  },
                  {
                    id: "authorized-tab",
                    label: "Authorized Tab",
                    path: "`/content/6_1/discovery_6_1/import_data_files/authorized_tab_6_1.md`"
                  },
                  {
                    id: "unauthorized-tab",
                    label: "Unauthorized Tab",
                    path: "`/content/6_1/discovery_6_1/import_data_files/unauthorized_tab_6_1.md`"
                  }
                ]
              },
              {
                id: "import-assetci-relations",
                label: "Import Asset/CI Relations",
                path: "`/content/6_1/discovery_6_1/import_data_files/import_assetci_relations_6_1.md`"
              },
              {
                id: "delete",
                label: "Delete",
                path: "`/content/6_1/discovery_6_1/import_data_files/delete_6_1.md`"
              },
              {
                id: "export",
                label: "Export",
                path: "`/content/6_1/discovery_6_1/import_data_files/export_6_1.md`"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "imported-assets",
    title: "Imported Assets",
    label: "Imported Assets",
    pages: [
      {
        id: "access-the-imported-assets",
        label: "Access the Imported Assets",
        path: "`/content/6_1/discovery_6_1/imported_assets/access_the_imported_assets_6_1.md`",
        subPages: [
          {
            id: "manage-imported-assets",
            label: "Manage Imported Assets",
            path: "`/content/6_1/discovery_6_1/imported_assets/manage_imported_assets_6_1.md`"
          },
          {
            id: "imported-asset-details",
            label: "Imported Asset Details",
            path: "`/content/6_1/discovery_6_1/imported_assets/imported_asset_details_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "ad-user-import-logs",
    title: "AD User Import Logs",
    label: "AD User Import Logs",
    pages: [
      {
        id: "ad-configuration-and-import",
        label: "AD Configuration and Import",
        path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/ad_configuration_and_import_6_1.md`",
        subPages: [
          {
            id: "access-the-ad-user-import-logs",
            label: "Access the AD User Import Logs",
            path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/access_the_ad_user_import_logs_6_1.md`"
          },
          {
            id: "view-import-log-details",
            label: "View Import Log Details",
            path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/view_import_log_details_6_1.md`",
            subPages: [
              {
                id: "details-tab",
                label: "Details Tab",
                path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/details_tab_6_1.md`"
              },
              {
                id: "tabs-for-extended-information",
                label: "Tabs for Extended Information",
                path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/tabs_for_extended_information_6_1.md`"
              }
            ]
          },
          {
            id: "customize-columns",
            label: "Customize Columns",
            path: "`/content/6_1/discovery_6_1/ad_azure_import_logs/customize_columns_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "azure-ad-user-import-logs",
    title: "Azure AD User Import Logs",
    label: "Azure AD User Import Logs",
    pages: [
      {
        id: "azure-ad-configuration-and-import",
        label: "Azure AD Configuration and Import",
        path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/azure_ad_configuration_and_import_6_1.md`",
        subPages: [
          {
            id: "access-the-azure-ad-user-import-logs",
            label: "Access the Azure AD User Import Logs",
            path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/access_the_azure_ad_user_import_logs_6_1.md`"
          },
          {
            id: "view-import-log-details",
            label: "View Import Log Details",
            path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/view_import_log_details_6_1.md`",
            subPages: [
              {
                id: "details-tab",
                label: "Details Tab",
                path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/details_6_1.md`"
              },
              {
                id: "key-information-displayed",
                label: "Key Information Displayed",
                path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/key_information_displayed_6_1.md`"
              },
              {
                id: "tabs-for-extended-information",
                label: "Tabs for Extended Information",
                path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/tabs_for_extended_information_6_1.md`"
              }
            ]
          },
          {
            id: "customize-columns",
            label: "Customize Columns",
            path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/customize_columns_6_1.md`"
          },
          {
            id: "delete-azure-ad-user-import-logs",
            label: "Delete Azure AD User Import Logs",
            path: "`/content/6_1/discovery_6_1/azure_ad_import_logs/delete_azure_ad_user_import_logs_6_1.md`"
          }
        ]
      }
    ]
  }
];

// ITSM sections
export const itsmSections = [
  {
    id: "configuration-management",
    title: "Configuration Management",
    label: "Configuration Management",
    pages: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "`/content/6_1/itsm_6_1/config_mngmt/dashboard_6_1.md`",
        subPages: [
          {
            id: "cmdb",
            label: "CMDB",
            path: "`/content/6_1/cmdb_6_1/cmdb_overview_6_1.md`",
            subPages: [
              {
                id: "access-cmdb",
                label: "Access CMDB",
                path: "`/content/6_1/itsm_6_1/change_mngmnt/access_cmdb_itsm_6_1.md`"
              },
              {
                id: "manage-cmdb",
                label: "Manage CMDB",
                path: "`/content/6_1/cmdb_6_1/manage_cmdb_6_1.md`"
              },
              {
                id: "view-and-edit-a-ci",
                label: "View and Edit a CI",
                path: "`/content/6_1/cmdb_6_1/view_and_edit_a_ci_6_1.md`"
              },
              {
                id: "ci-details-and-tabs",
                label: "CI Details and Tabs",
                path: "`/content/6_1/cmdb_6_1/ci_details_and_tabs_6_1.md`"
              }
            ]
          },
          {
            id: "sync-logs",
            label: "Sync Logs",
            path: "`/content/6_1/itsm_6_1/config_mngmt/sync_logs_6_1.md`"
          },
          {
            id: "tags",
            label: "Tags",
            path: "`/content/6_1/itsm_6_1/config_mngmt/tags_6_1.md`"
          },
          {
            id: "audits",
            label: "Audits",
            path: "`/content/6_1/itsm_6_1/config_mngmt/audits/audits_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "change-management",
    title: "Change Management",
    label: "Change Management",
    pages: [
      {
        id: "change-request",
        label: "Change Request",
        path: "`/content/6_1/itsm_6_1/change_mngmnt/change_request_6_1.md`"
      }
    ]
  },
  {
    id: "incident-management",
    title: "Incident Management",
    label: "Incident Management",
    pages: [
      {
        id: "about-incident-management",
        label: "About Incident Management",
        path: "`/content/6_1/itsm_6_1/incident_mngmnt/about_incident_mngmnt_6_1.md`"
      }
    ]
  },
  {
    id: "knowledge-management",
    title: "Knowledge Management",
    label: "Knowledge Management",
    pages: [
      {
        id: "about-knowledge-management",
        label: "About Knowledge Management",
        path: "`/content/6_1/itsm_6_1/knowledge_mngmt/about_knowledge_6_1.md`"
      }
    ]
  },
  {
    id: "problem-management",
    title: "Problem Management",
    label: "Problem Management",
    pages: [
      {
        id: "about-problem-management",
        label: "About Problem Management",
        path: "`/content/6_1/itsm_6_1/problem_mngmt/about_problem_mngmnt_6_1.md`"
      }
    ]
  },
  {
    id: "release-management",
    title: "Release Management",
    label: "Release Management",
    pages: [
      {
        id: "about-release-management",
        label: "About Release Management",
        path: "`/content/6_1/itsm_6_1/release_mngmt/about_release_mngmnt_6_1.md`"
      }
    ]
  },
  {
    id: "request-fulfillment",
    title: "Request Fulfillment",
    label: "Request Fulfillment",
    pages: [
      {
        id: "about-request-fulfillment",
        label: "About Request Fulfillment",
        path: "`/content/6_1/itsm_6_1/request_fulfillment/about_request_fulfillment_6_1.md`"
      }
    ]
  },
  {
    id: "service-portfolio",
    title: "Service Portfolio",
    label: "Service Portfolio",
    pages: [
      {
        id: "about-service-portfolio",
        label: "About Service Portfolio",
        path: "`/content/6_1/itsm_6_1/service_portfolio/about_service_portfolio_6_1.md`"
      }
    ]
  },
  {
    id: "runbook",
    title: "RunBook",
    label: "RunBook",
    pages: [
      {
        id: "runbook",
        label: "RunBook",
        path: "`/content/6_1/itsm_6_1/runbook/runbooks_6_1.md`"
      }
    ]
  }
];

// Vulnerability Management sections
export const vulnerabilityManagementSections = [
  {
    id: "vulnerability-management",
    title: "Vulnerability Management",
    label: "Vulnerability Management",
    pages: []
  }
];

// ITAM sections
export const itamSections = [
  {
    id: "configuration-management",
    title: "Configuration Management",
    label: "Configuration Management",
    pages: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "`/content/6_1/itsm_6_1/config_mngmt/dashboard_6_1.md`",
        subPages: [
          {
            id: "cmdb",
            label: "CMDB",
            path: "`/content/6_1/cmdb_6_1/cmdb_overview_6_1.md`",
            subPages: [
              {
                id: "access-cmdb",
                label: "Access CMDB",
                path: "`/content/6_1/itam_6_1/itam_cmdb/access_cmdb_itam_6_1.md`"
              },
              {
                id: "manage-cmdb",
                label: "Manage CMDB",
                path: "`/content/6_1/cmdb_6_1/manage_cmdb_6_1.md`"
              },
              {
                id: "view-and-edit-a-ci",
                label: "View and Edit a CI",
                path: "`/content/6_1/cmdb_6_1/view_and_edit_a_ci_6_1.md`"
              },
              {
                id: "ci-details-and-tabs",
                label: "CI Details and Tabs",
                path: "`/content/6_1/cmdb_6_1/ci_details_and_tabs_6_1.md`"
              }
            ]
          },
          {
            id: "sync-logs",
            label: "Sync Logs",
            path: "`/content/6_1/itsm_6_1/config_mngmt/sync_logs_6_1.md`"
          },
          {
            id: "tags",
            label: "Tags",
            path: "`/content/6_1/itsm_6_1/config_mngmt/tags_6_1.md`"
          },
          {
            id: "audits",
            label: "Audits",
            path: "`/content/6_1/itsm_6_1/config_mngmt/audits/audits_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "hardware-assets",
    title: "Hardware Assets",
    label: "Hardware Assets",
    pages: [
      {
        id: "hardware-assets",
        label: "Hardware Assets",
        path: "`/content/6_1/itam_6_1/hw_assets/hw_assets_6_1.md`"
      }
    ]
  },
  {
    id: "software-asset-management",
    title: "Software Asset Management",
    label: "Software Asset Management",
    pages: [
      {
        id: "about-software-asset-management",
        label: "About Software Asset Management",
        path: "`/content/6_1/itam_6_1/sw_asset_mngmt/about_sw_asset_mngmnt_6_1.md`",
        subPages: [
          {
            id: "software-asset",
            label: "Software Asset",
            path: "`/content/6_1/itam_6_1/sw_asset_mngmt/sw_assets_6_1.md`"
          },
          {
            id: "software-license-keys",
            label: "Software License Keys",
            path: "`/content/6_1/itam_6_1/sw_asset_mngmt/swlk_6_1.md`"
          },
          {
            id: "certificate-management",
            label: "Certificate Management",
            path: "`/content/6_1/itam_6_1/sw_asset_mngmt/certificate_mngmt_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "contract-management",
    title: "Contract Management",
    label: "Contract Management",
    pages: [
      {
        id: "contract-management",
        label: "Contract Management",
        path: "`/content/6_1/itam_6_1/contract_management/contract_mngmnt_6_1.md`"
      }
    ]
  },
  {
    id: "vendor-management",
    title: "Vendor Management",
    label: "Vendor Management",
    pages: [
      {
        id: "vendor-management",
        label: "Vendor Management",
        path: "`/content/6_1/itam_6_1/vendor_management/vendor_mngmnt_6_1.md`"
      }
    ]
  }
];

// Program/Project Management sections
export const programProjectManagementSections = [
  {
    id: "programs",
    title: "Programs",
    label: "Programs",
    pages: [
      {
        id: "programs",
        label: "Programs",
        path: "`/content/6_1/prog_proj_mngmnt_6_1/programs_6_1.md`",
        subPages: [
          {
            id: "program-dashboard",
            label: "Program Dashboard",
            path: "`/content/6_1/prog_proj_mngmnt_6_1/program_dashboard_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "projects",
    title: "Projects",
    label: "Projects",
    pages: [
      {
        id: "projects",
        label: "Projects",
        path: "`/content/6_1/prog_proj_mngmnt_6_1/projects_6_1.md`",
        subPages: [
          {
            id: "project-dashboard",
            label: "Project Dashboard",
            path: "`/content/6_1/prog_proj_mngmnt_6_1/project_dashboard_6_1.md`"
          }
        ]
      }
    ]
  }
];

// Self-Service sections
export const selfServiceSections = [
  {
    id: "self-service",
    title: "Self-Service",
    label: "Self-Service",
    pages: []
  }
];

// Risk Register sections
export const riskRegisterSections = [
  {
    id: "risk-register",
    title: "Risk Register",
    label: "Risk Register",
    pages: []
  }
];

// Reports sections
export const reportsSections = [
  {
    id: "reports",
    title: "Reports",
    label: "Reports",
    pages: []
  }
];

// Admin sections
export const adminSections = [
  {
    id: "organizational-details",
    title: "Organizational Details",
    label: "Organizational Details",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/admin_6_1/admin_org_details/about_org_details_6_1.md`"
      },
      {
        id: "cost-center",
        label: "Cost Center",
        path: "`/content/6_1/admin_6_1/admin_org_details/cost_center_6_1.md`"
      },
      {
        id: "departments",
        label: "Departments",
        path: "`/content/6_1/admin_6_1/admin_org_details/departments_6_1.md`",
        subPages: [
          {
            id: "members",
            label: "Members",
            path: "`/content/6_1/admin_6_1/admin_org_details/departments_members_6_1.md`"
          }
        ]
      },
      {
        id: "designations",
        label: "Designations",
        path: "`/content/6_1/admin_6_1/admin_org_details/designations_6_1.md`"
      },
      {
        id: "holidays",
        label: "Holidays",
        path: "`/content/6_1/admin_6_1/admin_org_details/holidays_6_1.md`"
      },
      {
        id: "locations",
        label: "Locations",
        path: "`/content/6_1/admin_6_1/admin_org_details/locations_6_1.md`"
      },
      {
        id: "operational-hours",
        label: "Operational Hours",
        path: "`/content/6_1/admin_6_1/admin_org_details/operational_hours_6_1.md`"
      },
      {
        id: "organizational-details",
        label: "Organizational Details",
        path: "`/content/6_1/admin_6_1/admin_org_details/organizational_details_6_1.md`"
      }
    ]
  },
  {
    id: "discovery",
    title: "Discovery",
    label: "Discovery",
    pages: [
      {
        id: "overview",
        label: "Overview",
        path: "`/content/6_1/admin_6_1/admin_discovery/admin_discovery_6_1.md`"
      },
      {
        id: "application-map",
        label: "Application Map",
        path: "`/content/6_1/admin_6_1/admin_discovery/application_map_6_1.md`",
        subPages: [
          {
            id: "client",
            label: "Client",
            path: "`/content/6_1/admin_6_1/admin_discovery/client_6_1.md`",
            subPages: [
              {
                id: "discovery-agents",
                label: "Discovery Agents",
                path: "`/content/6_1/admin_6_1/admin_discovery/client_discovery_agents_6_1.md`"
              },
              {
                id: "remote-install",
                label: "Remote Install",
                path: "`/content/6_1/admin_6_1/admin_discovery/client_remote_install_6_1.md`"
              },
              {
                id: "restart-client",
                label: "Restart Client",
                path: "`/content/6_1/admin_6_1/admin_discovery/client_restart_6_1.md`"
              },
              {
                id: "scan",
                label: "Scan",
                path: "`/content/6_1/admin_6_1/admin_discovery/client_scan_6_1.md`"
              }
            ]
          },
          {
            id: "correlation",
            label: "Correlation",
            path: "`/content/6_1/admin_6_1/admin_discovery/correlation_6_1.md`"
          },
          {
            id: "credentials",
            label: "Credentials",
            path: "`/content/6_1/admin_6_1/admin_discovery/credentials_6_1.md`",
            subPages: [
              {
                id: "details",
                label: "Details",
                path: "`/content/6_1/admin_6_1/admin_discovery/credentials_details_6_1.md`"
              },
              {
                id: "backup-file",
                label: "Backup File",
                path: "`/content/6_1/admin_6_1/admin_discovery/credentials_backup_file_6_1.md`"
              },
              {
                id: "flush-credential",
                label: "Flush Credential",
                path: "`/content/6_1/admin_6_1/admin_discovery/credentials_flush_6_1.md`"
              }
            ]
          },
          {
            id: "custom-patterns",
            label: "Custom Patterns",
            path: "`/content/6_1/admin_6_1/admin_discovery/custom_patterns_6_1.md`"
          },
          {
            id: "download-application",
            label: "Download Application",
            path: "`/content/6_1/admin_6_1/admin_discovery/downloading_discovery_6_1.md`"
          },
          {
            id: "import-templates",
            label: "Import Templates",
            path: "`/content/6_1/admin_6_1/admin_discovery/import_templates_6_1.md`"
          },
          {
            id: "ignore-adm-process",
            label: "Ignore ADM Process",
            path: "`/content/6_1/admin_6_1/admin_discovery/ignore_adm_process_6_1.md`"
          },
          {
            id: "ignore-process",
            label: "Ignore Process",
            path: "`/content/6_1/admin_6_1/admin_discovery/ignore_process_6_1.md`"
          },
          {
            id: "major-software",
            label: "Major Software",
            path: "`/content/6_1/admin_6_1/admin_discovery/major_software_6_1.md`"
          },
          {
            id: "monitoring-profile",
            label: "Monitoring Profile",
            path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_6_1.md`",
            subPages: [
              {
                id: "details",
                label: "Details",
                path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_details_6_1.md`"
              },
              {
                id: "frequency",
                label: "Frequency",
                path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_frequency_6_1.md`"
              },
              {
                id: "trigger-conditions",
                label: "Trigger Conditions",
                path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_trigger_conditions_6_1.md`"
              },
              {
                id: "action-details",
                label: "Action Details",
                path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_action_details_6_1.md`"
              },
              {
                id: "notifications",
                label: "Notifications",
                path: "`/content/6_1/admin_6_1/admin_discovery/mon_prof_notifications_6_1.md`"
              }
            ]
          },
          {
            id: "port-configuration",
            label: "Port Configuration",
            path: "`/content/6_1/admin_6_1/admin_discovery/port_config_process_6_1.md`"
          },
          {
            id: "probe-workflow",
            label: "Probe Workflow",
            path: "`/content/6_1/admin_6_1/admin_discovery/probe_workflow_6_1.md`"
          },
          {
            id: "probes",
            label: "Probes",
            path: "`/content/6_1/admin_6_1/admin_discovery/probes_6_1.md`"
          },
          {
            id: "scan-configuration",
            label: "Scan Configuration",
            path: "`/content/6_1/admin_6_1/admin_discovery/scan_configuration_6_1.md`"
          },
          {
            id: "sensors",
            label: "Sensors",
            path: "`/content/6_1/admin_6_1/admin_discovery/sensors_6_1.md`"
          },
          {
            id: "graphical-workflows",
            label: "Graphical Workflows",
            path: "`/content/6_1/admin_6_1/admin_discovery/graphical_workflows_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "sacm",
    title: "SACM",
    label: "SACM",
    pages: [
      {
        id: "blueprints",
        label: "Blueprints",
        path: "`/content/6_1/admin_6_1/admin_sacm/blueprints_6_1.md`"
      },
      {
        id: "custom-bsm-views",
        label: "Custom BSM Views",
        path: "`/content/6_1/admin_6_1/admin_sacm/custom_bsm_views_6_1.md`"
      },
      {
        id: "cmdb-graphical-workflow",
        label: "CMDB Graphical Workflow",
        path: "`/content/6_1/admin_6_1/admin_discovery/graphical_workflows_6_1.md`"
      },
      {
        id: "cmdb-properties",
        label: "CMDB Properties",
        path: "`/content/6_1/admin_6_1/admin_sacm/cmdb_properties_6_1.md`"
      },
      {
        id: "confidence-configuration",
        label: "Confidence Configuration",
        path: "`/content/6_1/admin_6_1/admin_sacm/confidence_config_6_1.md`"
      },
      {
        id: "duplicates-remediation",
        label: "Duplicates Remediation",
        path: "`/content/6_1/admin_6_1/admin_sacm/dups_remediation_6_1.md`"
      },
      {
        id: "export-ci-template",
        label: "Export CI Template",
        path: "`/content/6_1/admin_6_1/admin_sacm/export_ci_template_6_1.md`"
      },
      {
        id: "ip-connection-score-threshold",
        label: "IP Connection Score Threshold",
        path: "`/content/6_1/admin_6_1/admin_sacm/ip_conn_score_threshold_6_1.md`"
      },
      {
        id: "process-tags",
        label: "Process Tags",
        path: "`/content/6_1/admin_6_1/admin_sacm/process_tags_6_1.md`"
      },
      {
        id: "property-group",
        label: "Property Group",
        path: "`/content/6_1/admin_6_1/admin_sacm/property_group_6_1.md`"
      },
      {
        id: "relationship-types",
        label: "Relationship Types",
        path: "`/content/6_1/admin_6_1/admin_sacm/relationship_types_6_1.md`"
      },
      {
        id: "software-license-validity-check",
        label: "Software License Validity Check",
        path: "`/content/6_1/admin_6_1/admin_sacm/sw_lic_validity_check_6_1.md`"
      },
      {
        id: "software-usage-report",
        label: "Software Usage Report",
        path: "`/content/6_1/admin_6_1/admin_sacm/software_usage_report_6_1.md`"
      }
    ]
  },
  {
    id: "users",
    title: "Users",
    label: "Users",
    pages: [
      {
        id: "ad-configuration",
        label: "AD Configuration",
        path: "`/content/6_1/admin_6_1/admin_users/ad_imp_auth_6_1.md`"
      },
      {
        id: "azure-ad-configuration",
        label: "Azure AD Configuration",
        path: "`/content/6_1/admin_6_1/admin_users/azure_ad_config_6_1.md`"
      },
      {
        id: "saml-configuration",
        label: "SAML Configuration",
        path: "`/content/6_1/admin_6_1/admin_users/saml_config_6_1.md`"
      },
      {
        id: "time-track-reports",
        label: "Time Track Reports",
        path: "`/content/6_1/admin_6_1/admin_users/time_track_reports_6_1.md`"
      },
      {
        id: "user-groups",
        label: "User Groups",
        path: "`/content/6_1/admin_6_1/admin_users/user_groups_6_1.md`"
      },
      {
        id: "user-roles",
        label: "User Roles",
        path: "`/content/6_1/admin_6_1/admin_users/user_roles_6_1.md`"
      },
      {
        id: "users",
        label: "Users",
        path: "`/content/6_1/admin_6_1/admin_users/users_6_1.md`"
      }
    ]
  },
  {
    id: "management-functions",
    title: "Management Functions",
    label: "Management Functions",
    pages: [
      {
        id: "change-management",
        label: "Change Management",
        path: "`/content/6_1/admin_6_1/admin_change_mngmnt/about_change_mngmnt_6_1.md`"
      },
      {
        id: "contract-management",
        label: "Contract Management",
        path: "`/content/6_1/admin_6_1/admin_contract_mngmt/about_contract_mngmnt_6_1.md`"
      },
      {
        id: "event-management",
        label: "Event Management",
        path: "`/content/6_1/admin_6_1/admin_event_mngmnt/about_event_mngmnt_6_1.md`"
      },
      {
        id: "hardware-asset-management",
        label: "Hardware Asset Management",
        path: "`/content/6_1/admin_6_1/admin_hardware_asset_mngmnt/about_hw_asset_mngmnt_6_1.md`"
      },
      {
        id: "incident-management",
        label: "Incident Management",
        path: "`/content/6_1/admin_6_1/admin_incident_mngmnt/about_incident_mngmnt_6_1.md`"
      },
      {
        id: "knowledge-management",
        label: "Knowledge Management",
        path: "`/content/6_1/admin_6_1/admin_knowledge_mngmnt/about_knowledge_mngmnt_6_1.md`"
      },
      {
        id: "problem-management",
        label: "Problem Management",
        path: "`/content/6_1/admin_6_1/admin_problem_mngmnt/about_problem_mngmnt_6_1.md`"
      },
      {
        id: "procurement",
        label: "Procurement",
        path: "`/content/6_1/admin_6_1/admin_procurement/about_procurement_6_1.md`",
        subPages: [
          {
            id: "procurement-properties",
            label: "Procurement Properties",
            path: "`/content/6_1/admin_6_1/admin/admin_functions_new_6_1.md`"
          },
          {
            id: "procurement-property-group",
            label: "Procurement Property Group",
            path: "`/content/6_1/admin_6_1/admin_procurement/procurement_property_group_6_1.md`"
          }
        ]
      },
      {
        id: "project-management",
        label: "Project Management",
        path: "`/content/6_1/admin_6_1/admin_project_mngmnt/about_project_mngmnt_6_1.md`"
      },
      {
        id: "release-management",
        label: "Release Management",
        path: "`/content/6_1/admin_6_1/admin_release_mngmnt/about_release_mngmnt_6_1.md`"
      },
      {
        id: "request-management",
        label: "Request Management",
        path: "`/content/6_1/admin_6_1/admin_request_mngmnt/about_request_mngmnt_6_1.md`"
      },
      {
        id: "vendor-management",
        label: "Vendor Management",
        path: "`/content/6_1/admin_6_1/admin_vendor_mngmnt/about_vendor_mngmnt_6_1.md`"
      }
    ]
  },
  {
    id: "integrations",
    title: "Integrations",
    label: "Integrations",
    pages: [
      {
        id: "cherwell-credential",
        label: "Cherwell Credential",
        path: "`/content/6_1/admin_6_1/admin_integrations/cherwell_credential_6_1.md`",
        subPages: [
          {
            id: "cherwell-mappings",
            label: "Cherwell Mappings",
            path: "`/content/6_1/admin_6_1/admin_integrations/cherwell_mappings_6_1.md`"
          }
        ]
      },
      {
        id: "infoblox-configuration",
        label: "Infoblox Configuration",
        path: "`/content/6_1/admin_6_1/admin_integrations/infoblox_config_6_1.md`"
      },
      {
        id: "ivanti-credentials",
        label: "Ivanti Credentials",
        path: "`/content/6_1/admin_6_1/admin_integrations/ivanti_credentials_6_1.md`",
        subPages: [
          {
            id: "ivanti-mappings",
            label: "Ivanti Mappings",
            path: "`/content/6_1/admin_6_1/admin_integrations/ivanti_mappings_6_1.md`"
          }
        ]
      },
      {
        id: "jira-credentials",
        label: "Jira Credentials",
        path: "`/content/6_1/admin_6_1/admin_integrations/jira_credentials_6_1.md`",
        subPages: [
          {
            id: "jira-asset-mappings",
            label: "Jira Asset Mappings",
            path: "`/content/6_1/admin_6_1/admin_integrations/jira_mappings_6_1.md`"
          }
        ]
      },
      {
        id: "servicenow-credentials",
        label: "ServiceNow Credentials",
        path: "`/content/6_1/admin_6_1/admin_integrations/servicenow_credentials_6_1.md`",
        subPages: [
          {
            id: "servicenow-mappings",
            label: "ServiceNow Mappings",
            path: "`/content/6_1/admin_6_1/admin_integrations/servicenow_mappings_6_1.md`"
          }
        ]
      }
    ]
  },
  {
    id: "others",
    title: "Others",
    label: "Others",
    pages: [
      {
        id: "announcements",
        label: "Announcements",
        path: "`/content/6_1/admin_6_1/admin_other/announcements_6_1.md`"
      },
      {
        id: "business-rules",
        label: "Business Rules",
        path: "`/content/6_1/admin_6_1/admin_other/business_rules_6_1.md`"
      },
      {
        id: "custom-reports",
        label: "Custom Reports",
        path: "`/content/6_1/admin_6_1/admin_other/custom_reports_6_1.md`"
      },
      {
        id: "documentation-and-tester",
        label: "Documentation and Tester",
        path: "`/content/6_1/admin_6_1/admin_other/documentation_tester_6_1.md`"
      },
      {
        id: "inbox-configuration-for-itsm-ticket-management",
        label: "Inbox Configuration for ITSM Ticket Management",
        path: "`/content/6_1/admin_6_1/admin_event_mngmnt/mailbox_configuration_6_1.md`"
      },
      {
        id: "kpis",
        label: "KPIs",
        path: "`/content/6_1/admin_6_1/admin_other/kpis_6_1.md`"
      },
      {
        id: "reports",
        label: "Reports",
        path: "`/content/6_1/reports_6_1/reports_6_1.md`"
      },
      {
        id: "role-access",
        label: "Role Access",
        path: "`/content/6_1/admin_6_1/admin_other/role_access_6_1.md`"
      },
      {
        id: "service-level-agreements",
        label: "Service Level Agreements",
        path: "`/content/6_1/admin_6_1/admin_other/sla_6_1.md`"
      },
      {
        id: "smtp-configuration",
        label: "SMTP Configuration",
        path: "`/content/6_1/admin_6_1/admin_other/smtp_config_6_1.md`"
      },
      {
        id: "risk-score-calculator",
        label: "Risk Score Calculator",
        path: "`/content/6_1/admin_6_1/admin_other/risk_score_calculator_6_1.md`"
      },
      {
        id: "graphical-workflows",
        label: "Graphical Workflows",
        path: "`/content/6_1/admin_6_1/admin_discovery/graphical_workflows_6_1.md`"
      }
    ]
  }
];

// Release Notes sections
export const releaseNotesSections = [
  {
    id: "release-notes",
    title: "Release Notes",
    label: "Release Notes",
    pages: [
      {
        id: "actions-required",
        label: "Actions Required",
        path: "`/content/6_1/release_notes_6_1/actions_required_6_1.md`"
      },
      {
        id: "summary",
        label: "Summary",
        path: "`/content/6_1/release_notes_6_1/summary_6_1.md`"
      },
      {
        id: "discovery",
        label: "Discovery",
        path: "`/content/6_1/release_notes_6_1/discovery_6_1.md`"
      },
      {
        id: "cmdb",
        label: "CMDB",
        path: "`/content/6_1/release_notes_6_1/cmdb_6_1.md`"
      },
      {
        id: "itsm-and-itam",
        label: "ITSM and ITAM",
        path: "`/content/6_1/release_notes_6_1/itsm_itam_6_1.md`"
      },
      {
        id: "integration",
        label: "Integration",
        path: "`/content/6_1/release_notes_6_1/integration_6_1.md`"
      },
      {
        id: "admin",
        label: "Admin",
        path: "`/content/6_1/release_notes_6_1/admin_6_1.md`"
      },
      {
        id: "reports",
        label: "Reports",
        path: "`/content/6_1/release_notes_6_1/reports_6_1.md`"
      },
      {
        id: "msp",
        label: "MSP",
        path: "`/content/6_1/release_notes_6_1/msp_6_1.md`"
      },
      {
        id: "beta",
        label: "Beta",
        path: "`/content/6_1/release_notes_6_1/beta_6_1.md`"
      },
      {
        id: "discovery-application",
        label: "Discovery Application",
        path: "`/content/6_1/release_notes_6_1/discovery_application_6_1.md`"
      }
    ]
  }
];

// Support sections
export const supportSections = [
  {
    id: "support",
    title: "Support",
    label: "Support",
    pages: []
  }
];

// Helper function to get sections for a specific module
export function getSectionsForModule(moduleId: string) {
  switch (moduleId) {
    case "my-dashboard":
      return myDashboardSections;
    case "cmdb":
      return cmdbSections;
    case "discovery-scan":
      return discoveryScanSections;
    case "itsm":
      return itsmSections;
    case "vulnerability-management":
      return vulnerabilityManagementSections;
    case "itam":
      return itamSections;
    case "programproject-management":
      return programProjectManagementSections;
    case "self-service":
      return selfServiceSections;
    case "risk-register":
      return riskRegisterSections;
    case "reports":
      return reportsSections;
    case "admin":
      return adminSections;
    case "release-notes":
      return releaseNotesSections;
    case "support":
      return supportSections;
    default:
      return [];
  }
}
