/**
 * docs-search.ts
 *
 * Client-side search over the statically-generated search index
 * (public/search-index.json, produced at build time by scripts/build-search-index.ts).
 *
 * No external APIs, no backend, no runtime services.
 * The index is fetched once on first search and cached for the session.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SearchIndexEntry {
  /** Unique path-derived ID (used as React key and for deduplication). */
  id: string;
  /** Label-slugified ID for in-app navigation (matches useDocGraphNav page.id). */
  navId: string;
  /** Document title (from first H1 or page label). */
  title: string;
  /** Module ID (e.g., "admin"). */
  module: string;
  /** Module display label (e.g., "Admin"). */
  moduleLabel: string;
  /**
   * Section ID within the module.
   * Field name matches the JSON generated by build-search-index.ts.
   * Previously incorrectly declared as `sectionId` (causing silent undefined at runtime).
   */
  section: string;
  /** Relative file path from content root (e.g., "admin/ad_configuration/...md"). */
  filePath: string;
  /** H2/H3 headings in the document. */
  headings: string[];
  /** Heading IDs matching the headings array (same slug algorithm as MDXRenderer). */
  headingIds?: string[];
  /** Cleaned plain-text excerpt (~280 chars). Falls back to title if body is empty. */
  excerpt: string;
  /** Human-readable breadcrumb (e.g., "Admin > Ad Configuration"). */
  breadcrumb: string;
}

export interface SearchResult extends SearchIndexEntry {
  /** Relevance score — higher is more relevant. Not shown to users. */
  score: number;
  /** The heading that matched the query, if applicable. */
  matchedHeading?: string;
  /** The anchor ID for the matched heading (for deep linking). */
  matchedHeadingId?: string;
}

/** A result from searching within the current page (This page mode). */
export interface CurrentPageResult {
  /** Section heading text. */
  heading: string;
  /** The actual DOM element ID for anchor navigation. */
  headingId: string;
  /** Parent heading for context (e.g., "Configuration" for a nested h3). */
  parentHeading?: string;
  /** Short text snippet from the section body. */
  snippet: string;
  /** Relevance score. */
  score: number;
}

// ---------------------------------------------------------------------------
// Index loading
// ---------------------------------------------------------------------------

let cachedIndex: SearchIndexEntry[] | null = null;
let loadPromise: Promise<SearchIndexEntry[]> | null = null;

/**
 * Load and cache the search index.
 * Resolves the correct base URL for both local dev and GitHub Pages deployment.
 */
async function loadSearchIndex(): Promise<SearchIndexEntry[]> {
  if (cachedIndex) return cachedIndex;
  if (loadPromise) return loadPromise;

  loadPromise = (async () => {
    // Base URL from Vite — handles both / (dev) and /FeatureDocsite/ (GitHub Pages)
    const base = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '');
    const url = `${base}/search-index.json`;

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to load search index (HTTP ${response.status})`);
    }

    const data: SearchIndexEntry[] = await response.json();
    cachedIndex = data;
    return data;
  })();

  return loadPromise;
}

/**
 * Preload the search index in the background.
 * Call this when the search dialog is opened to reduce perceived latency.
 */
export function preloadSearchIndex(): void {
  loadSearchIndex().catch(() => {
    // Silent — will surface as an error when the user actually searches
  });
}

// ---------------------------------------------------------------------------
// Suggested questions (derived from the live index)
// ---------------------------------------------------------------------------

/**
 * Action verbs that indicate a heading is a task ("Add User", "Configure SNMP", …).
 * Requires a whole-word match ("<verb> <rest>" or exactly "<verb>") to avoid
 * false positives like "runbooks" matching "run".
 */
const ACTION_VERBS = [
  'add', 'create', 'edit', 'update', 'delete', 'remove', 'configure', 'run',
  'schedule', 'set up', 'link', 'submit', 'export', 'import',
  'enable', 'disable', 'assign', 'upload', 'install', 'integrate',
  'generate', 'approve', 'reject', 'clone', 'deploy', 'filter',
];

/** Strip markdown bold/italic/code markers so they don't appear in questions. */
function stripMarkdown(text: string): string {
  return text.replace(/\*\*/g, '').replace(/\*/g, '').replace(/`/g, '').trim();
}

/** True when `text` (lowercase) starts with an action verb as a whole word. */
function startsWithActionVerb(text: string): boolean {
  return ACTION_VERBS.some(v => text === v || text.startsWith(`${v} `));
}

/**
 * Titles that make poor questions (section overviews, meta pages).
 * Entries whose titles start with these words are skipped during sampling.
 */
const SKIP_TITLE_PREFIXES = ['about', 'overview', 'introduction', 'welcome', 'faq', 'core'];

/**
 * Convert a single index entry into a "How do I…?" question.
 * Returns null for entries that would produce an awkward question (callers skip them).
 */
function entryToQuestion(entry: SearchIndexEntry): string | null {
  const cleanTitle = stripMarkdown(entry.title);
  const titleLower = cleanTitle.toLowerCase();

  // Skip section-overview pages ("About X", "Overview", etc.)
  if (SKIP_TITLE_PREFIXES.some(p => titleLower === p || titleLower.startsWith(`${p} `))) {
    return null;
  }

  // Prefer an action-oriented heading — "Add User" → "How do I add user?"
  const actionHeading = entry.headings
    .map(stripMarkdown)
    .find(h => startsWithActionVerb(h.toLowerCase()));
  if (actionHeading) {
    return `How do I ${actionHeading.toLowerCase()}?`;
  }

  // Fall back to the page title
  return startsWithActionVerb(titleLower)
    ? `How do I ${titleLower}?`
    : `How do I manage ${titleLower}?`;
}

/**
 * Sample n question-formatted prompts from the cached search index.
 * Returns null when the index hasn't been loaded yet — call preloadSearchIndex first.
 * Questions spread across different modules for variety.
 */
export function sampleDocQuestions(n = 4): string[] | null {
  if (!cachedIndex || cachedIndex.length === 0) return null;

  // Group by module so we can spread questions across modules
  const byModule = new Map<string, SearchIndexEntry[]>();
  for (const entry of cachedIndex) {
    const list = byModule.get(entry.module) ?? [];
    list.push(entry);
    byModule.set(entry.module, list);
  }

  const modules = [...byModule.keys()].sort(() => Math.random() - 0.5);
  const questions: string[] = [];

  // Round-robin across modules until we have n questions; skip unanswerable entries
  let i = 0;
  while (questions.length < n && i < cachedIndex.length * 2) {
    const mod = modules[i % modules.length];
    const entries = byModule.get(mod)!;
    const entry = entries[Math.floor(Math.random() * entries.length)];
    const q = entryToQuestion(entry);
    if (q && !questions.includes(q)) questions.push(q);
    i++;
  }

  return questions;
}

/**
 * Async version — waits for the index to load if it hasn't yet.
 * Use this in the dialog open handler when the index may not be cached yet.
 */
export async function sampleDocQuestionsAsync(n = 4): Promise<string[]> {
  await loadSearchIndex();
  return sampleDocQuestions(n) ?? [];
}

// ---------------------------------------------------------------------------
// Stop words
// ---------------------------------------------------------------------------

/**
 * Common English stop words that carry no domain signal.
 * Filtering these prevents "how", "do", "i", "a", "in" from inflating
 * scores for irrelevant pages via substring matches.
 */
const STOP_WORDS = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'by', 'can',
  'do', 'does', 'for', 'from', 'get', 'got', 'had', 'has', 'have',
  'how', 'i', 'if', 'in', 'is', 'it', 'its', 'me', 'my', 'not',
  'of', 'on', 'or', 'so', 'that', 'the', 'their', 'them', 'then',
  'there', 'they', 'this', 'to', 'up', 'was', 'we', 'what', 'when',
  'where', 'which', 'who', 'will', 'with', 'would', 'you',
  // Greeting prefixes — filtered so "hi, how do I configure SLA?" scores cleanly
  'hi', 'hello', 'hey', 'howdy', 'hola',
]);

/**
 * Test whether `text` contains `term` as a whole word (not as a substring
 * inside a longer word). Prevents "in" from matching "information".
 * Falls back to simple `includes` for terms shorter than 3 chars that
 * survived stop-word filtering (e.g. domain acronyms like "ci").
 */
function containsWord(text: string, term: string): boolean {
  if (term.length < 3) return text.includes(term);
  return new RegExp(`(?:^|[^a-z0-9])${term}(?:[^a-z0-9]|$)`).test(text);
}

// ---------------------------------------------------------------------------
// Synonym / abbreviation expansion
// ---------------------------------------------------------------------------

/**
 * Virima-specific abbreviation and synonym map.
 *
 * When a query token matches a key, the mapped terms are ADDED to the
 * effective search terms (additive — the original token is preserved).
 * This ensures "sr" scores against "service request" pages even though
 * the exact string "sr" rarely appears in documentation text.
 *
 * Keys must be lowercase. Values are space-separated expansion terms.
 */
export const QUERY_SYNONYMS: Record<string, string> = {
  // ITSM / service desk
  'sr':           'service request',
  'ticket':       'service request',
  'tickets':      'service request',
  'incident':     'incident management',
  'incidents':    'incident management',
  'change':       'change request',
  'changes':      'change request',
  // CMDB / asset
  'ci':           'configuration item',
  'cis':          'configuration item',
  'asset':        'cmdb',
  'assets':       'cmdb',
  // Knowledge base
  'kb':           'knowledge base',
  'article':      'knowledge base',
  // Vulnerability
  'vm':           'vulnerability management',
  'vuln':         'vulnerability management',
  // Risk
  'rr':           'risk register',
  // SLA
  'sla':          'service level agreement',
  'slas':         'service level agreement',
};

/**
 * Expand recognized abbreviations/synonyms in a token list.
 * Expansion is additive — original tokens are not removed.
 */
function expandSynonyms(tokens: string[]): string[] {
  const result = [...tokens];
  for (const token of tokens) {
    const expansion = QUERY_SYNONYMS[token];
    if (expansion) {
      for (const t of expansion.split(/\s+/)) {
        if (t.length >= 2 && !STOP_WORDS.has(t) && !result.includes(t)) {
          result.push(t);
        }
      }
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Module boost signals
// ---------------------------------------------------------------------------

/**
 * Maps unambiguous query terms to module label substrings.
 * When any effective term matches a key, all results from the matched module
 * receive a +20 score boost — reducing cross-module noise at zero token cost.
 *
 * First matching signal wins. Only include terms with clear module affinity.
 */
export const MODULE_BOOST_SIGNALS: Record<string, string> = {
  // Full module name signals
  'admin':          'admin',
  'administration': 'admin',
  'itsm':           'itsm',
  'cmdb':           'cmdb',
  'discovery':      'discovery',
  'vulnerability':  'vulnerability',
  'risk':           'risk',
  'report':         'report',
  'reports':        'report',
  'self-service':   'self-service',
  'selfservice':    'self-service',
  'dashboard':      'dashboard',
  // Abbreviations → module boosts
  // "ci" (2-char) uses substring matching and would hit "incident" pages;
  // the module boost counteracts this by favouring CMDB.
  'ci':             'cmdb',
  'cis':            'cmdb',
  'sr':             'itsm',
  'vm':             'vulnerability',
  'vuln':           'vulnerability',
  'rr':             'risk',
};

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

/**
 * Search the documentation index for the given query.
 *
 * Scoring weights (per meaningful term — stop words filtered out):
 *   Exact title match   : 100
 *   Title starts with   : 60
 *   Title contains term : 40
 *   Heading contains    : 25
 *   Breadcrumb contains : 15
 *   Module label matches: 10
 *   Excerpt contains    : 5
 *
 * Results are capped at 12.
 */
export async function searchDocs(query: string): Promise<SearchResult[]> {
  const trimmed = query.trim();
  if (!trimmed) return [];

  const index = await loadSearchIndex();

  // Filter stop words and very short tokens; keep minimum 1 term even if all filtered
  const allTerms = trimmed.toLowerCase().split(/\s+/).filter(Boolean);
  const terms = allTerms.filter(t => t.length >= 2 && !STOP_WORDS.has(t));
  const effectiveTerms = terms.length > 0 ? terms : allTerms.slice(0, 3);

  // Expand abbreviations/synonyms (additive — originals kept)
  const expandedTerms = expandSynonyms(effectiveTerms);

  // Detect module boost signal: first effective term that maps to a module wins
  let boostedModuleFragment: string | null = null;
  for (const term of expandedTerms) {
    const sig = MODULE_BOOST_SIGNALS[term];
    if (sig) { boostedModuleFragment = sig; break; }
  }

  const results = index
    .map((entry): SearchResult | null => {
      let score = 0;
      let matchedHeading: string | undefined;
      let matchedHeadingId: string | undefined;

      const titleLower = entry.title.toLowerCase();
      const excerptLower = entry.excerpt.toLowerCase();
      const breadcrumbLower = entry.breadcrumb.toLowerCase();
      const moduleLower = entry.moduleLabel.toLowerCase();

      for (const term of expandedTerms) {
        // Title — highest weight (whole-word match to avoid substring noise)
        if (titleLower === term) {
          score += 100;
        } else if (titleLower.startsWith(term)) {
          score += 60;
        } else if (containsWord(titleLower, term)) {
          score += 40;
        }

        // Headings (whole-word)
        const headingIdx = entry.headings.findIndex(h =>
          containsWord(h.toLowerCase(), term)
        );
        if (headingIdx !== -1) {
          score += 25;
          if (!matchedHeading) {
            matchedHeading = entry.headings[headingIdx];
            matchedHeadingId = entry.headingIds?.[headingIdx];
          }
        }

        // Breadcrumb / module (whole-word)
        if (containsWord(breadcrumbLower, term)) score += 15;
        if (containsWord(moduleLower, term)) score += 10;

        // Body excerpt (whole-word)
        if (containsWord(excerptLower, term)) score += 5;
      }

      // Module boost: query contained a clear module signal → favour that module
      const moduleMatches = boostedModuleFragment !== null &&
        moduleLower.includes(boostedModuleFragment);
      if (moduleMatches) score += 20;

      return score > 0 ? { ...entry, score, matchedHeading, matchedHeadingId } : null;
    })
    .filter((r): r is SearchResult => r !== null)
    .sort((a, b) => b.score - a.score)
    .slice(0, 12);

  return results;
}

// ---------------------------------------------------------------------------
// This Page search — DOM-based, article content only
// ---------------------------------------------------------------------------

/**
 * Search within the current page's article content.
 *
 * Scoped strictly to the <article> container — excludes nav, TOC, footer,
 * feedback widgets, and all non-article shell content.
 *
 * Uses real DOM heading IDs (set by MDXRenderer via generateSlug) for
 * reliable anchor navigation.
 */
export function searchCurrentPage(query: string): CurrentPageResult[] {
  const trimmed = query.trim();
  if (!trimmed) return [];

  const article = document.querySelector('article');
  if (!article) return [];

  const allPageTerms = trimmed.toLowerCase().split(/\s+/).filter(Boolean);
  const pageTerms = allPageTerms.filter(t => t.length >= 2 && !STOP_WORDS.has(t));
  const terms = pageTerms.length > 0 ? pageTerms : allPageTerms.slice(0, 3);
  const headings = article.querySelectorAll('h2[id], h3[id], h4[id]');

  if (headings.length === 0) return [];

  const results: CurrentPageResult[] = [];
  let lastH2: string | undefined;

  headings.forEach((heading) => {
    const text = heading.textContent?.trim() ?? '';
    const id = heading.id;
    const level = heading.tagName.toLowerCase();
    const textLower = text.toLowerCase();

    // Track parent h2 for context on nested headings
    if (level === 'h2') lastH2 = text;
    const parentHeading = level !== 'h2' ? lastH2 : undefined;

    // Extract body snippet: text between this heading and the next heading
    let snippet = '';
    let sibling = heading.nextElementSibling;
    const bodyParts: string[] = [];
    while (sibling && !['H2', 'H3', 'H4'].includes(sibling.tagName)) {
      const t = sibling.textContent?.trim();
      if (t) bodyParts.push(t);
      sibling = sibling.nextElementSibling;
    }
    snippet = bodyParts.join(' ').substring(0, 200);
    const snippetLower = snippet.toLowerCase();

    // Score this section
    let score = 0;
    for (const term of terms) {
      if (textLower === term) score += 100;
      else if (textLower.startsWith(term)) score += 60;
      else if (textLower.includes(term)) score += 40;

      if (snippetLower.includes(term)) score += 10;
    }

    if (score > 0) {
      results.push({ heading: text, headingId: id, parentHeading, snippet, score });
    }
  });

  return results.sort((a, b) => b.score - a.score).slice(0, 10);
}
